### PR TITLE
player experiment: "custom read aloud"

### PR DESCRIPTION
**Pull request by danielweck**
Experiment with https://github.com/thephilgray/custom-readaloud-plugin

### CODE REVIEW

**Comment by danielweck** [comment]
Test with this URL:
https://raw.githack.com/w3c/sync-media-pub/feature/custom-read-aloud-player/samples/single-document/index.html

**Comment by marisademeglio** [comment]
Cool! One thing though - did the sync points change in the narration document, or is the player not respecting the clip boundaries? The original version that I posted purposely excluded the audio for "read by <so and so> for librivox.org".

**Comment by danielweck** [comment]
Note: both demos (Marisa's own experiment, and this one which uses an existing lib) currently hard-code the CSS "active" classes. These should be declared somewhere so that a playback engine (irrespective of the implementation details) can discover what class names to use.

**Comment by danielweck** [comment]
Note: this implementation requires a single audio resource, whereas (I think) the sync-media-narration JSON can reference different audio files (?).

**Comment by danielweck** [comment]
The playback model in this implementation does not seem to be capable of handling clip begin *and* end. I other words, the injected "play head"  is equivalent to clip-begin only, there is an assumption that audio clips are contiguous within a given audio stream.

**Comment by danielweck** [comment]
Bug? The text highlight only syncs when audio playback reaches the known beginning of an audio fragment. There is stale highlighted text when scrubbing the playback bar directly in the audio controls UI.

**Comment by danielweck** [comment]
I filed an issue here:
https://github.com/thephilgray/custom-readaloud-plugin/issues/21

**Comment by danielweck** [comment]
I filed another issue:
https://github.com/thephilgray/custom-readaloud-plugin/issues/22

**Comment by danielweck** [comment]
Note how this implementation enables keyboard navigation by setting an ARIA `role` of `button` and `tabindex` on all synchronized elements. This behaviour should probably activated "on demand" to avoid UX issues, i.e. activate specifically during the synch'ed text/audio experience. But otherwise, I like the idea :)

**Comment by marisademeglio** [comment]
Closing as this would overwrite the existing demo. Suggest putting in a different folder.

**Comment by danielweck** [comment]
For sure. Let's delete my branch as well to avoid future housekeeping. The code diff is trivial and will be preserved in this PR for posterity anyway :)

**Pull request closed without merging**
